apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bruslans.brus.lan.com
spec:
  group: brus.lan.com
  names:
    kind: Bruslan
    listKind: BruslanList
    plural: bruslans
    singular: bruslan
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bruslan-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bruslan-operator
  template:
    metadata:
      labels:
        name: bruslan-operator
    spec:
      containers:
        - name: bruslan-operator
          image: bruslan/demo-operator
          command:
          - bruslan-operator
          imagePullPolicy: Always
